name:                hsort
version:             0.1.0.0
github:              "faithanalog/hsort"
license:             MIT
author:              "Artemis Everfree"
maintainer:          "artemis@artemis.sh"
copyright:           "2022 Artemis Everfree"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/faithanalog/hsort#readme>

dependencies:
- base >= 4.7 && < 5
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hsort:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsort

tests:
  hsort-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsort
    - QuickCheck
    - text
    - quickcheck-instances
